services:
  postgrest:
    image: postgrest/postgrest:v10.1.2
    environment:
      PGRST_DB_URI: "postgres://postgres:${POSTGRES_PASSWORD}@postgres/postgres"
      PGRST_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - 3000:3000
  postgres:
    image: ghcr.io/ninanor/followit-live-data-feed-server:main
    build: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
