services:
  postgrest:
    image: postgrest/postgrest:v10.1.2
    environment:
      PGRST_DB_URI: "postgres://postgres:${POSTGRES_PASSWORD}@postgres/postgres"
      PGRST_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - 3000:3000
  dbmate:
    build: db
    command: --wait --no-dump-schema up
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
